### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by AkshithaReddy1899** [fabian7593/CountryAPI#11]
Hi. firstly, I loved the country API so much that it inspired me to build a project around it. I am almost done with my project and now I discover there is no CORS support to it, which kind of stops the user from getting the response. I would really appreciate if the API has CORS support.

**Comment by tatd3v** [comment]
Hi! I have the same issue and I'm looking for an API without the CORS issue. Did you find something?

**Comment by AkshithaReddy1899** [comment]
> Hi! I have the same issue and I'm looking for an API without the CORS issue. Did you find something?

Hello. [REST Countries](https://restcountries.com/) might help
