### ISSUE TITLE
Api change without version change

### ISSUE THREAD

**Issue by alexeygolev** [fabian7593/CountryAPI#4]
First of all thank you for the service. 
One tiny problem though. Today I find out that the api has changed (all the keys have been captialized) without changing the api version. Is this something I should expect from the endpoint as you're still in a state of flux, or can I rely on it? I mean you offering it for free, I'm not complaining. But it would be nice to know if you're planning to drastically change the api often

**Comment by fabian7593** [comment]
Hello @alexeygolev, yeah its true, Im sorry for this issue.
I want to change the version api the next week and leave ha last version too.
Anyway this error never comeback.
The change its only for best practices rest api.

PD: how the repository has a few stars I dont think anyone was using it yet. So Sorry.

**Comment by alexeygolev** [comment]
Thank you very much, hopefully you'll get more traction soon:-)
